# -*- coding: utf-8 -*-
"""mut4(1.3.4).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_swgZAta_jmIm0osg4PwUyUhZg1nXSvD
"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/

!git clone -b colab https://github.com/Myway-person-classifier/v1.3_ik.git

# Commented out IPython magic to ensure Python compatibility.
# %cd v1.3_ik

# 1. requirements.txt에서 qwen3_seqcls_infonce 제거 확인
!grep -v "qwen3_seqcls_infonce" requirements.txt > requirements_clean.txt
!mv requirements_clean.txt requirements.txt

# 2. 또는 직접 확인
!cat requirements.txt

!pip install torch==2.9.0 torchaudio==2.9.0 --index-url https://download.pytorch.org/whl/cu126
!pip uninstall -y wandb

# 1. protobuf 버전 갈등 해결 (GetPrototype AttributeError 해결)
!pip install "protobuf<4.0.0" --force-reinstall

# 2. bitsandbytes 코랩 최적화 버전 설치
!pip install -U bitsandbytes

# 3. 필수 라이브러리 재설치 (의존성 꼬임 방지)
!pip install accelerate peft transformers datasets

# 4. (선택사항) bitsandbytes가 CUDA 라이브러리를 못 찾을 때를 대비한 경로 설정
import os
os.environ["LD_LIBRARY_PATH"] += ":/usr/local/cuda/lib64"

!pip install -r requirements.txt

# 작업 디렉토리 설정
import os
PROJECT_ROOT = '/content/drive/MyDrive/v1.3_ik'
os.chdir(PROJECT_ROOT)

# 환경 변수 설정
os.environ['DATA_DIR'] = f'{PROJECT_ROOT}/data'
os.environ['OUTPUT_DIR'] = f'{PROJECT_ROOT}/outputs'

# GPU 확인
!nvidia-smi
import torch
print(f"CUDA available: {torch.cuda.is_available()}")

# 데이터 파일 확인
import pandas as pd
data_dir = os.environ.get('DATA_DIR', './data')
if os.path.exists(os.path.join(data_dir, 'train.csv')):
    train_df = pd.read_csv(os.path.join(data_dir, 'train.csv'))
    print(f"✅ train.csv: {len(train_df)} rows")
elif os.path.exists(os.path.join(data_dir, 'augmented_merged_reviews.csv')):
    train_df = pd.read_csv(os.path.join(data_dir, 'augmented_merged_reviews.csv'))
    print(f"✅ augmented_merged_reviews.csv: {len(train_df)} rows")
else:
    print("❌ 데이터 파일을 찾을 수 없습니다!")

import os
import sys

PROJECT_ROOT = '/content/drive/MyDrive/v1.3_ik'
file_path = f'{PROJECT_ROOT}/trainers/fold_trainer.py'

# 1. 파일 내용 확인
print("="*60)
print("현재 파일 내용 (86-100번째 줄):")
print("="*60)
with open(file_path, 'r', encoding='utf-8') as f:
    lines = f.readlines()
    for i in range(85, min(100, len(lines))):
        marker = "❌" if 'evaluation_strategy' in lines[i] else "✅"
        print(f"{marker} {i+1:3d}: {lines[i].rstrip()}")

# 2. evaluation_strategy 검색
print("\n" + "="*60)
print("evaluation_strategy 검색 결과:")
print("="*60)
with open(file_path, 'r', encoding='utf-8') as f:
    content = f.read()
    if 'evaluation_strategy' in content:
        print("❌ 아직 evaluation_strategy가 있습니다!")
        print("\n발견된 위치:")
        for i, line in enumerate(content.split('\n'), start=1):
            if 'evaluation_strategy' in line:
                print(f"  Line {i}: {line.strip()}")
    else:
        print("✅ evaluation_strategy가 없습니다!")

# 3. eval_strategy 검색
print("\n" + "="*60)
print("eval_strategy 검색 결과:")
print("="*60)
if 'eval_strategy' in content:
    print("✅ eval_strategy가 있습니다!")
    for i, line in enumerate(content.split('\n'), start=1):
        if 'eval_strategy' in line:
            print(f"  Line {i}: {line.strip()}")
else:
    print("❌ eval_strategy가 없습니다!")

from types import SimpleNamespace
from trainers.fold_trainer import FoldTrainer
from transformers import AutoTokenizer
import os

# wandb 비활성화
os.environ['WANDB_DISABLED'] = 'true'
os.environ['WANDB_MODE'] = 'disabled'

# 또는
os.environ['WANDB_SILENT'] = 'true'

PROJECT_ROOT = '/content/drive/MyDrive/v1.3_ik'

# Fold 0 학습
cfg = SimpleNamespace(
    data_dir=f'{PROJECT_ROOT}/data',
    output_dir=f'{PROJECT_ROOT}/outputs',  # 출력 디렉토리 명시
    is_submission=False,
    is_kfold=True,
    k_fold=4,
    fold_idx=0,  # 0, 1, 2, 3 순차로 변경
    val_ratio=0.2,
    use_paragraph=True,
    add_title=False,
    save_dir="v1.3_fold",  # constants_phase4 디렉토리 사용
    save_name="fold0",
    model_name="HybridAvsH",
    embedding_model="kykim/funnel-kor-base",
    num_labels=1,
    num_heads=8,
    num_layers=4,
    dim_feedforward=2048,
    hidden_size=512,
    dropout=0.0,
    use_bpr_loss=True,
    bpr_loss_weight=0.25,
    use_infonce_loss=True,
    lambda_cl=0.1,
    temperature=0.07,
    num_train_epochs=10,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    gradient_accumulation_steps=2,
    learning_rate=3e-5,
    warmup_ratio=0.1,
    weight_decay=1e-3,
    logging_steps=10,
    max_length=256,
    split_valid_by_paragraph=False,
    save_fold_logits=True,
    local_rank=-1,
)

# 데이터 파일 존재 확인
train_path = os.path.join(cfg.data_dir, "train.csv")
alt_path = os.path.join(cfg.data_dir, "augmented_merged_reviews.csv")
if not os.path.exists(train_path) and not os.path.exists(alt_path):
    raise FileNotFoundError(
        f"데이터 파일을 찾을 수 없습니다. 다음 중 하나가 필요합니다:\n"
        f"  - {train_path}\n"
        f"  - {alt_path}"
    )
else:
    print(f"✅ 데이터 파일 확인: {train_path if os.path.exists(train_path) else alt_path}")

# 출력 디렉토리 생성
os.makedirs(cfg.output_dir, exist_ok=True)
print(f"✅ 출력 디렉토리: {cfg.output_dir}")

trainer = FoldTrainer(cfg)
trainer.train_fold(0)  # fold_idx를 1, 2, 3으로 변경하여 반복

import os

from types import SimpleNamespace
from trainers.fold_trainer import FoldTrainer

PROJECT_ROOT = '/content/drive/MyDrive/v1.3_ik'

# Fold 0 학습
cfg = SimpleNamespace(
    data_dir=f'{PROJECT_ROOT}/data',
    output_dir=f'{PROJECT_ROOT}/outputs',
    is_submission=False,
    is_kfold=True,
    k_fold=4,
    fold_idx=0,  # 0, 1, 2, 3 순차로 변경
    val_ratio=0.2,
    use_paragraph=True,
    add_title=False,
    save_dir="v1.3_fold",
    save_name="fold0",
    # model - bert-kor-base 사용
    model_name="HybridAvsH",  # ✅ HybridAvsH 모델
    embedding_model="kykim/bert-kor-base",  # ✅ bert-kor-base
    num_labels=1,
    num_heads=8,
    num_layers=4,
    dim_feedforward=2048,
    hidden_size=512,  # bert-kor-base는 자동으로 설정됨 (무시 가능)
    dropout=0.0,
    # loss
    use_bpr_loss=True,
    bpr_loss_weight=0.25,
    use_infonce_loss=True,
    lambda_cl=0.1,
    temperature=0.07,
    # train
    num_train_epochs=10,
    per_device_train_batch_size=8,  # bert-kor-base는 작은 모델이므로 배치 사이즈 8 가능
    per_device_eval_batch_size=8,
    gradient_accumulation_steps=2,
    learning_rate=3e-5,
    warmup_ratio=0.1,
    weight_decay=1e-3,
    logging_steps=10,
    max_length=256,
    # misc
    split_valid_by_paragraph=False,
    save_fold_logits=True,
    local_rank=-1,
)

# 데이터 파일 존재 확인
train_path = os.path.join(cfg.data_dir, "train.csv")
alt_path = os.path.join(cfg.data_dir, "augmented_merged_reviews.csv")
if not os.path.exists(train_path) and not os.path.exists(alt_path):
    raise FileNotFoundError(
        f"데이터 파일을 찾을 수 없습니다. 다음 중 하나가 필요합니다:\n"
        f"  - {train_path}\n"
        f"  - {alt_path}"
    )
else:
    print(f"✅ 데이터 파일 확인: {train_path if os.path.exists(train_path) else alt_path}")

# 출력 디렉토리 생성
os.makedirs(cfg.output_dir, exist_ok=True)
print(f"✅ 출력 디렉토리: {cfg.output_dir}")

trainer = FoldTrainer(cfg)
trainer.train_fold(0)  # fold_idx를 1, 2, 3으로 변경하여 반복

